version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=simple_blog_api
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=simple_blog_api
      - POSTGRES_PORT=5432
  
